### ISSUE TITLE
Research and Daiquiris Broken by latest FAF patch

### ISSUE THREAD

**Issue by Renegade1993** [The-Balthazar/BrewLAN#36]
Not sure if you are supporting the compatibility for FAF, but the latest patch that was pushed yesterday breaks it. Commander never gets spawned into the game if you run the module.

Let me know if you need any other info.

Thanks for your efforts!

**Comment by Toviorus** [comment]
Can confirm the issue.

**Comment by Era4721** [comment]
Can also confirm the issue,

**Comment by The-Balthazar** [comment]
Fixed https://github.com/The-Balthazar/BrewLAN/commit/3a6c0dd7e89df7cde8a8bea2d579b1f9f591ebc8

**Comment by wnnmaw** [comment]
Looks like this issue still occurs. BrewLAN and Daiquiris are the only mods running. It is isolated to FAF, running through Steam directly has no issue.

Game patch 3756
FAF v2022.11.0
BrewLAN v0.8.9.9

Let me know if you need any additional info.
